server:
  port: ${:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: ${CATALOG-URL}
          predicates: [Path=/api/catalog/** ]
        - id: basket
          uri: ${BASKET-URL}
          predicates: [ Path=/api/basket/** ]
        - id: pricing
          uri: ${PRICING-URL}
          predicates: [ Path=/api/pricing/** ]