server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: ${CATALOG_URL:http://localhost:9001}
          predicates: [Path=/api/catalog/** ]
        - id: basket
          uri: ${BASKET_URL:http://localhost:9002}
          predicates: [ Path=/api/basket/** ]
        - id: pricing
          uri: ${PRICING_URL:http://localhost:9003}
          predicates: [ Path=/api/pricing/** ]